apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: quiz
type: Opaque
data:
  mongo-uri: bW9uZ29kYitzcnY6Ly92aXZhaGphaF9kYl91c2VyOlJuVzdpTXkya0F3SEhIZEZAY2x1c3RlcjAubW54c2o3Zi5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMA==
